/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// Keep this synchronized with the file routes.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as M1000RouteImport } from './routes/m1000'
import { Route as IndexRouteImport } from './routes/index'

const AboutRoute = AboutRouteImport.update({ id: '/about', path: '/about', getParentRoute: () => rootRouteImport } as any)
const CompaniesRoute = CompaniesRouteImport.update({ id: '/companies', path: '/companies', getParentRoute: () => rootRouteImport } as any)
const InsightsRoute = InsightsRouteImport.update({ id: '/insights', path: '/insights', getParentRoute: () => rootRouteImport } as any)
const M1000Route = M1000RouteImport.update({ id: '/m1000', path: '/m1000', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/companies': typeof CompaniesRoute
  '/insights': typeof InsightsRoute
  '/m1000': typeof M1000Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/companies': typeof CompaniesRoute
  '/insights': typeof InsightsRoute
  '/m1000': typeof M1000Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/companies': typeof CompaniesRoute
  '/insights': typeof InsightsRoute
  '/m1000': typeof M1000Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/companies' | '/insights' | '/m1000'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/companies' | '/insights' | '/m1000'
  id: '__root__' | '/' | '/about' | '/companies' | '/insights' | '/m1000'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompaniesRoute: typeof CompaniesRoute
  InsightsRoute: typeof InsightsRoute
  M1000Route: typeof M1000Route
  SynaRoute: typeof SynaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/', path: '/', fullPath: '/', preLoaderRoute: typeof IndexRouteImport, parentRoute: typeof rootRouteImport }
    '/about': { id: '/about', path: '/about', fullPath: '/about', preLoaderRoute: typeof AboutRouteImport, parentRoute: typeof rootRouteImport }
    '/companies': { id: '/companies', path: '/companies', fullPath: '/companies', preLoaderRoute: typeof CompaniesRouteImport, parentRoute: typeof rootRouteImport }
    '/insights': { id: '/insights', path: '/insights', fullPath: '/insights', preLoaderRoute: typeof InsightsRouteImport, parentRoute: typeof rootRouteImport }
    '/m1000': { id: '/m1000', path: '/m1000', fullPath: '/m1000', preLoaderRoute: typeof M1000RouteImport, parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AboutRoute,
  CompaniesRoute,
  InsightsRoute,
  M1000Route,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
